language: julia
os:
    - linux
    - osx
julia:
    - release
    - nightly
notifications:
    email: false

matrix:
  allow_failures:
    - julia: nightly

before_script:
  - wget https://github.com/sam81/Psychophysics_test_data/archive/master.zip
  - unzip master.zip -d ../
  - mv ../Psychophysics_test_data-master ../Psychophysics_test_data
  

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Psychophysics"); Pkg.test("Psychophysics"; coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("Psychophysics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'